### ISSUE TITLE
pandoc-docx-pagebreak doesn't work with pandoc 2.0.2

### ISSUE THREAD

**Issue by atanasj** [alexstoick/pandoc-docx-pagebreak#1]
Hi,

Have you experienced this? Is there any way to resolve this?

Thanks,
Atanas

**Comment by alexstoick** [comment]
@atanasj - This is what I have on my machine.

```
=> pandoc -v
pandoc 2.0
Compiled with pandoc-types 1.17.0.5, texmath 0.9.1, skylighting 0.3
```


Do you have an error trace?

**Comment by atanasj** [comment]
HI @alexstoick. Sorry for the tardy reply. I was not installing this correctly. I have only just got back to this, and it works perfectly. Version details are: 

```
pandoc 2.1
Compiled with pandoc-types 1.17.3, texmath 0.10.1, skylighting 0.5.1
```  

So good new! Plus, this is a super helpful script. Thanks for your work and sharing!!
